# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  # Declare a Node orb to simplify Node.js-related configurations
  node: circleci/node@5.2

# Define jobs for different steps of the workflow
jobs:
  test-js:
    # Use the pre-defined node orb job to set up Node.js environment
    executor: node/default
    steps:
      - checkout  # Check out the code from the repository

      # Install dependencies using npm
      - run:
          name: Install Dependencies
          command: npm install

      # Run tests or scripts
      - run:
          name: Run JavaScript Tests
          command: npm test

# Define workflows to orchestrate the execution of jobs
workflows:
  version: 2
  sample:
    jobs:
      - test-js  # Run the test-js job
