# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  # Use the Node orb to simplify Node.js-related configurations
  node: circleci/node@4.1

# Define jobs for different steps of the workflow
jobs:
  run-js-project:
    # Use the node orb job to set up Node.js environment
    executor: node/default
    steps:
      - checkout  # Check out the code from the repository

      # Install dependencies if needed
      # - run:
      #     name: Install Dependencies
      #     command: npm install

      # Run the JavaScript file
      - run:
          name: Run EMI Calculator
          command: node index.js

# Define workflows to orchestrate the execution of jobs
workflows:
  version: 2
  emi_calculator:
    jobs:
      - run-js-project  # Run the run-js-project job
