version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  run-emi-calculator:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Serve HTML and CSS files
          command: |
            echo 'Starting server...'
            npx http-server -p 8080
          background: true
      - run:
          name: Run JavaScript for EMI Calculator
          command: |
            echo 'Running EMI calculator...'
            node index.js
      - persist_to_workspace:
          root: .
          paths:
            - index.js
            - index.html
            - styles.css

workflows:
  version: 2
  emi-calculator:
    jobs:
      - run-emi-calculator
