version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run EMI Calculator
          command: npm run test

workflows:
  version: 2
  emi-calculator:
    jobs:
      - test
